# Generated by Django 5.0.6 on 2024-10-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
