# Generated by Django 5.0.6 on 2024-10-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_service', '0002_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
