# Generated by Django 5.0.6 on 2024-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_service', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
