# Generated by Django 5.0.6 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_service', '0005_inventorymovement_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_threshold',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
